[project]
name = "football-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "selenium>=4.38.0",
    "webdriver-manager>=4.0.2",
]
